# Generated by Django 3.1.2 on 2020-12-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='characters',
            field=models.ManyToManyField(blank=True, to='inventory.Character'),
        ),
    ]
